version: "3"
services:
 websocketserver:
  image: websocket-server:latest
  ports:
   - 2345:2345
  environment:
   - PYTHONPATH=/workspace
 vuefrontend:
  image: vue-frontend:latest
  depends_on:
   - websocketserver
  ports:
   - 8080:8080
  
  