from enum import Enum

""" [summary] Enum classes that specifies state machine's states
 """


class State(Enum):
    GREETING = 1
    TUTORIAL_OR_EXPERIMENT = 2
    INTRODUCTION_START = 3
    INGREDIENT_SELECTION = 4
    MIX_STRONG_ACID = 5
    EXPLAIN_STRONG_ACID = 6
    MIX_STRONG_BASE = 7
    EXPLAIN_STRONG_BASE = 8
    MIX_WEAK_ACID = 9
    EXPLAIN_WEAK_ACID = 10
    PRACTICE_START = 11
    COLLECT_SUBSTANCES = 12
    IDENTIFY_PH = 13
    PRACTICE_COLLECTING = 14
    PRACTICE_CYCLE = 15
    PRACTICE_CHILD_QUESTION = 16
    PRACTICE_CHATBOT_QUESTION = 17
    PRACTICE_INFORMATION = 18
    PRACTICE_RESET = 19
    PRACTICE_CLARIFICATION = 20
