from enum import Enum

""" [summary] Enum classes that specifies state machine's states
 """


class State(Enum):
    GREETING = 1
    TUTORIAL_OR_EXPERIMENT = 2
    INTRODUCTION_START = 3
    INGREDIENT_SELECTION = 4
    INDICATOR_EXPLANATION = 5
    WAIT_TO_SELECTION = 6
    MIX_STRONG_ACID = 7
    EXPLAIN_STRONG_ACID = 8
    QUESTION_STRONG_ACID = 9
    WAIT_TO_POUR_BASE = 10
    MIX_STRONG_BASE = 11
    EXPLAIN_STRONG_BASE = 12
    MIX_WATER = 13
    EXPLAIN_WATER = 14
    MIX_WEAK_ACID = 15
    QUESTION_WEAK_ACID = 16
    EXPLAIN_WEAK_ACID = 17
    GO_TO_PRACTICE = 18
    PRACTICE_START = 19
    COLLECT_SUBSTANCES = 20
    IDENTIFY_PH = 21
    PRACTICE_COLLECTING = 22
    PRACTICE_CYCLE = 23
    PRACTICE_CHILD_QUESTION = 24
    PRACTICE_CHATBOT_QUESTION = 25
    PRACTICE_INFORMATION = 26
    PRACTICE_RESET = 27
    PRACTICE_CLARIFICATION = 28
