from enum import Enum

class State(Enum):
    GREETING = 1
    INTRODUCTION_START = 2
    ACID_SELECTION = 3
    BASE_SELECTION = 4
    GUIDED_REASONING = 5
    GUIDED_POURING = 6
    PRACTICE_COLLECTING = 7
    PRACTICE_CYCLE = 8
    PRACTICE_CHILD_QUESTION = 9
    PRACTICE_CHATBOT_QUESTION = 10
    PRACTICE_INFORMATION = 11
    PRACTICE_RESET = 12
    PRACTICE_CLARIFICATION = 13