from enum import Enum

class State(Enum):
    GREETING = 1
    INTRODUCTION_START = 2
    ACID_SELECTION = 3
    BASE_SELECTION = 4
    WATER_SELECTION = 5
    GUIDED_REASONING = 6
    GUIDED_POURING = 7
    PRACTICE_COLLECTING = 8
    PRACTICE_CYCLE = 9
    PRACTICE_CHILD_QUESTION = 10
    PRACTICE_CHATBOT_QUESTION = 11
    PRACTICE_INFORMATION = 12
    PRACTICE_RESET = 13
    PRACTICE_CLARIFICATION = 14